version: '3.8'

services:
  app:
    build: .
    container_name: undg
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=undg
      - DB_PASSWORD=undg
      - DB_NAME=undg

  db:
    image: postgres:15-alpine
    container_name: undg_db
    environment:
      POSTGRES_USER: undg
      POSTGRES_PASSWORD: undg
      POSTGRES_DB: undg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
